name: mno_commons
description: This package provide utilities (JSON, io, Href, UriTemplate, etc...) for other mno_xxx packages.
version: 0.1.2
homepage: https://github.com/Mantano/mno_commons_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^4.0.6
  crypto: ^3.0.1
  dartx: ^1.0.0
  dfunc: ^0.10.0
  equatable: ^2.0.3
  fimber: ^0.7.0
  meta: ^1.7.0
  path: ^1.8.0
  universal_io: ^2.0.4

dev_dependencies:
  coverage: ^1.12.0
  lints: ^5.1.1
  test: ^1.20.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
